version: '3.8'

services:
  # The MongoDB Database Service
  mongo-db:
    image: mongo:latest
    container_name: oneclickalpha-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Your Application Service
  app:
    build: .
    ports:
      - "3001:3001" # Change 3000 to your app's actual port if different
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017/oneclickalpha
    depends_on:
      - mongo-db

volumes:
  mongo-data:
